name: Build Kernel and ISO with Docker

on:
  push:
    branches: [ main, 'stable/13' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Dyna Kernel and ISO for ${{ matrix.target_arch }}
    runs-on: ubuntu-latest  # Use Ubuntu as the host runner for Docker
    strategy:
      fail-fast: false
      matrix:
        target_arch: [ amd64, aarch64 ]
        include:
          - target_arch: amd64
            target: amd64
          - target_arch: aarch64
            target: arm64

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker pull freebsd:14.1  # Pull the FreeBSD image for the desired version

      - name: Run Build in FreeBSD Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace freebsd:13.2 /bin/sh -c "
            pkg install -y bmake llvm14 lld14 libarchive git &&
            export PATH=/usr/local/llvm14/bin:\$PATH &&
            mkdir -p /workspace/build &&
            export MAKEOBJDIRPREFIX=/workspace/build &&
            ./tools/build/make.py TARGET=${{ matrix.target }} TARGET_ARCH=${{ matrix.target_arch }} kernel-toolchain &&
            ./tools/build/make.py TARGET=${{ matrix.target }} TARGET_ARCH=${{ matrix.target_arch }} buildkernel &&
            cd ./release &&
            bmake TARGET=${{ matrix.target }} TARGET_ARCH=${{ matrix.target_arch }} release &&
            bmake TARGET=${{ matrix.target }} TARGET_ARCH=${{ matrix.target_arch }} DISTDIR=/workspace/build release
          "

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ matrix.target }}-${{ matrix.target_arch }}
          path: build/sys/${{ matrix.target }}.${{ matrix.target_arch }}/GENERIC/kernel

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso-${{ matrix.target }}-${{ matrix.target_arch }}
          path: build/release/*.iso
